apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: APIKey
metadata:
  name: my-stack-key
spec:
  forProvider:
    name: 'Crossplane'
    role: 'Admin'
    cloudStackRef:
      name: my-stack
  providerConfigRef:
    name: grafana-cloud-provider
  writeConnectionSecretToRef:
    name: my-stack-secret
    namespace: crossplane-system